name: Deploy Nuxt App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3
       
         
      - name: Build and run Docker container
        run: |
        
          docker build -t vitrine .
          docker stop vitrine || true
          docker rm vitrine || true
          docker run -d --name vitrine -p 3005:3005 vitrine

      
